; Language and accent options https://gtts.readthedocs.io/en/latest/module.html#localized-accents
[TTS]
language = en
top_level_domain = co.uk

[audio]
target_samplerate = 48000
input_device = CABLE Input (VB-Audio Virtual Cable)
output_device = Headphones audio-technica (Realtek(R) Audio)

[window]
window_height = 220
window_width = 400
always_on_top = True